python run_qa.py \
  --model_name_or_path deepset/minilm-uncased-squad2 \
  --dataset_name squad \
  --do_train \
  --per_device_train_batch_size 4 \
  --learning_rate 3e-5 \
  --num_train_epochs 1 \
  --max_seq_length 384 \
  --doc_stride 128 \
  --max_steps 20 \
  --use_mps_device \
  --output_dir ./debug_squad/